theme = "ayu_mirage"
#flexoki_dark

[editor]
line-number = 'relative'
cursorline = true
auto-format = false
rulers = [100]
#bufferline = 'always'

[editor.statusline]
left = ["mode", "spinner",  "read-only-indicator", ]
center = ["file-name", "file-modification-indicator"]
right = ["diagnostics", "selections", "register", "position-percentage", "spacer", "separator", "total-line-numbers", "file-encoding"]

[editor.cursor-shape]
normal = "bar"
insert = "bar"
select = "block"

[editor.whitespace.render]
space = "all"
tab = "all"
nbsp = "all"
nnbsp = "all"

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true

[editor.smart-tab]
enable = false
supersede-menu = true

[editor.inline-diagnostics]
cursor-line = "warning"
other-lines = "error"
